### ISSUE TITLE
Improvements for legacy formspec system

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#11785]
### TODO

- [ ] `list` to support image styling (with press+hover states).
- [ ] `{table,scrollbar}options` and `listcolors` to be migrated to `StyleSpec`.
- [ ] Any element that support image styling should also support _animated_ image styling.
- [ ] `tooltip` drawing should involve the `GUIHyperText` class. Not having a basic image support in tooltips is a shame in 2021.

### Unfinished

- https://github.com/minetest/minetest/pull/11345
- https://github.com/minetest/minetest/pull/10265

Cc: @v-rob @rubenwardy

**Comment by Zughy** [comment]
Closing this issue as it sounds more like a personal to-do list (as a GitHub project)
