### ISSUE TITLE
Flexible Physics

### ISSUE THREAD

**Issue by ExeVirus** [minetest/minetest#13879]
### Problem

> Minetest has one set of physics: WASD walk and jump, with an option zero-gravity flight.

Every other form of physics is either a form of the above physics, or overridden with server-sent positions and velocities. 

We've probably all experienced riding a minecart or using a boat or bicycle on a server before - and noticed just how bad the experience can be (lag, glitchy, not fun).

### Solutions

The solution is modifiable client-side physics. 

## Current plan (Subject to Change - will edit as it changes)

- **Single player only for now**
- At startup, mod/game mods are read, they have an API call they can use: `minetest.register_physics("name_of_physics","lua_filename.lua")`
- At runtime, the server can call `player:set_physics("name_of_physics")` to change the player's current physics style
- At runtime, the server can call `player:set_physics_info("name_of_physics", lua_table)` to provide arbitrary data to that client to control that physics style
- This one registered lua file will handle camera control + player physics.

## Later plan: Anti-cheat dehardcoding
Same as above, except server-side only, and you merely register a callback for that physics' specific anticheat:
- At runtime, the server can call `minetest.register_anti_cheat("name_of_physics", callback)`

### Alternatives

- use server sent control packets only, the current solution
- add a few more hardcoded physics options, such as flying vehicle, driving vehicle, momentum/sliding, point-style gravity.
    - Bad Idea because it is inflexible, and puts all the onus on the Engine - this is not something we want to control, looking at the number of issues complaining about our 1 supported physics style... #9446, #9520, #10139, #12201, #6755, #6123, #3822, #5861

### Additional context

1. To work on anything other than single player - we will have to find a method for SSCSM - #8057
    - The goal of this issue will NOT be to implement a safe method for SSCSM, there are many methods to accomplish this, such as signed code (distributed trust), central trust, fantastic sandboxing, manual review (buyer beware), etc. 
    - The goal of this issue will be to provide a REASON for SSCSM to exist - new gameplay features and styles.
2. I will be working a full workday today on this task and create a merge request at the end for a prototype/finished product for what this will/can look like.
3. I will periodically add comments to this issue with my design decisions and process for both my own tracking and yours...
4. I will focus on just enabling this for single-player with a few demo physics styles (default, maybe a mario-2d, vehicle-style, ice, etc.)
5. Keep in mind that just making physics editable won't be enough, this will eventually require CSM camera control #13052, and anti-cheat control #6852, those three should be most of what's needed to pull off flexible physics in Minetest.
6. There will likely be a requirement to also handle flexible SSCSM object physics at some point too, but that is a discussion for after this is implemented and has community support/merged.

**Comment by ExeVirus** [comment]
# Design Overview

I will attempt to use a single class per server and client design.

#### Server Class

- [ ] Tracks registered physics styles and their associated lua file
- [ ] Tracks per-player physics settings (one lua table per player)
- [ ] checks that the provided lua files can actually be used before trying to run (validation)

#### Client Class

- [ ] Probably just preload each lua physics file into their own sub_environment within the same global client lua environment
    - Alternatively, multiple lua environments can be used
    - Or even one can be reset and reload if the delay isn't too bad
- [ ] Handle pushing needed inputs into the callback
    - [ ] position
    - [ ] orientation
    - [ ] velocity
    - [ ] user inputs (mouse, keyboard)
    - [ ] server data (lua_table of flexible data)
    - [ ] Look direction (if different from orientation)
    - possibly collision info for nearby nodeboxes/terrain
- [ ] Handle reading outputs, safely
    - [ ] position
    - [ ] orientation
    - [ ] velocity
    - [ ] camera position
    - [ ] camera fov
    - [ ] camera orientation
    - [ ] camera velocity (all camera stuff can be relative to player)
    - [ ] boolean for whether camera is relative to player or world
    - possibly collision info

## Tasks

- [ ] Server Side Class
- [ ] Client Side Class
- [ ] Server Side lua-api connection
- [ ] Server-sent lua media (.lua file support - actually trivial to send :D )
- [ ] Hack-method to disable anti-cheat if it's an issue for this demo/task
- [ ] Documentation, code commnents, cleanup, coding style. the actual professional part...
- [ ] Lua documentation, lua_api.txt, etc. 
- [ ] Apprently Josiah thinks our developer getting started sucks, take notes on what would have been nice to know and have easily accesible...

**Comment by ExeVirus** [comment]
# Server Class

# Public Interfaces
```c++
bool register_physics(std::string physics_name, std::string filename)                // returns false on invalid lua file, warns on overwrite
bool overwrite_player_physics_detail(std::string player_name, std::string physics_name, JSON lua_table_detail) // fail if not valid lua table or player doesn't exist
bool get_player_physics_detail(std::string player_name, std::string physics_name,  JSON lua_table_detail)      // fail if not valid lua table or player doesn't exist
bool get_registered_physics(std::unordered_map& result)                              // name, filename, maybe should return a json so we can send it over the network, not sure yet
bool change_player_physics(std::string player_name, std::string physics_name)        // false if player or physics doesn't exist
```

# Internal Tasks

```c++
bool validatePhysics(std::string filename) // false if not valid physics file, creates and destorys a mini lua environment for the task
```

# Internal State

```c++
std::unordered_map<std::string, std::string> name_to_physics_file_lookup
std::unordered_map<std::string, std::unordered_map<std::string, JSON (lua table)>> playername_to_physics_detail_lookup
```

**Comment by ExeVirus** [comment]
# Client Class

# Public Interfaces
```c++
bool change_player_physics(std::string physics_name, JSON detail); // called by network stack ideally...
bool get_player_physics_tick(PlayerClass& thingWeReadAndOutputTo, Inputs mouseAndKeyboard); //can fail for so many reasons....
```

# Internal Tasks

```c++
bool loadEnvironment(std::string filename);
bool loadInputs(PlayerClass& thingWeReadAndOutputTo, Inputs mouseAndKeyboard);
bool getOutputsViaCallback(PlayerClass& thingWeReadAndOutputTo); //calls the luaFile callback and reads the results safely
bool Lock()     // probably have to protect this lua_environment
bool Unlock()   // from multithreaded doom
```

# Internal State

```c++
lua_env physicsLuaEnvironment;     // hopefully reusable, may have to have a vector of environments or something stupid haha
std::string current_physics_name;  // probably a more performant way to store this, like assign physics to integers and network send that, so client just knows numbers....
std::mutex;                        // the classic mutex of doom
std::unordered_map<std::string, std::string> name_to_physics_file_lookup;
std::unordered_map<std::string, JSON (lua table)> physics_name_to_detail_lookup;
```

**Comment by ExeVirus** [comment]
# Actual Designed Use

### 1: Server mods place lua files in media:
```
mod/media/mario_phyiscs.lua
mod/media/planet_phyics.lua
mod/media/car_physics.lua
```

### 2: Server mods register physics
```lua
minetest.register_phyiscs("mario", "mario_physics.lua")
minetest.register_phyiscs("planet", "planet_phyics.lua")
minetest.register_phyiscs("car", "car_physics.lua")
```
### 3: Later, during runtime
```lua
minetest.on_player_join(function(player)
    player:set_physics_info("mario", 
        {
            speed=5.0,
            jump=5.0,
            running_jump=10.0,
            super_jump=15.0
        })
    player:set_physics("mario")
end)
```

**Comment by ExeVirus** [comment]
Phew, I think that's all the design work before I deep dive into our actual codebase.

Some nagging questions I am thinking about include:
- modders will want access to the full client side API while in this physics callback I bet (for sounds and effects, heck even chat)
- How to safely sandbox this so that each physics file doesn't infect the CSM environment... that's going to be tricky if we want to be performant...
- Wonder what math libraries we should expose
- Hopefully we have nlohman::json support, and hopefully our network code can send compressed json strings across the network already using zstd....
- I still haven't looked at how we handle collisions... oh this is not going to be pretty I'm sure...

 Breaktime!

**Comment by ExeVirus** [comment]
jsoncpp works too, not quite as featured but decent enough for my purposes. Thank goodness we already have lua_table to json converters 😈

**Comment by ExeVirus** [comment]
# Minetest Engine in a nutshell

### main.cpp - main()
  1. Loads Arguments
  2. Initializes paths
  3. Handles command line args for user help (list games, list worlds, etc)
  4. Library Init (Networking, seed random, curl, gettext)
  5. Starts benchmarking, if enabled
  6. Either runs as headless server or standard client, which may or may not run a single player server

### Client

1. ClientLauncher().run()
    1. init_args() further
    2. init_engine()
        1. EventQueue
        2. Rendering Engine
    3. Create main menu
    4. Handle Main Menu
        1. Calls the_game() to run game
2. Game.cpp game.startup()
    1. Init()
        1. Creates textures, shaders, ItemDefManager, NodeDefManager, EventManager (for game), Sound
        2. Creates singleplayerserver if applicable
    2. createClient()
        1. Connect to server, get server content, update local caches after data received
        2. Create camera, clouds, skybox
        3. initGui()
            1. Create debug text, chat text, info text, etc. (gameui.cpp)
            2. create GuiChatConsole
        4. Create HUD
        5. Initialize RenderingEngine
3.  Game.cpp game.run() [cleanest function so far]
    1. updateDynamicInfo() - UI scaling, screen size, etc. looks like sent to server
    2. update Debug render stats
    3. update punch timers
    4. checkConnection() or fail
    5. handleCallbacks() or fail
        1. These include disconnect, password_change, volume change, key config change
    6. process texture and shader queues (shader is empty for now)
    7. updateProfilers()
    8. ProcessUserInput() handles callbacks for each key, read from inputHandler's keycache variable
    9. updateCameraDirection() (before movement, otherwise it looks like lag or something)
    10. updatePlayerControl() passes keys, camera pitch+yaw, movement speed, and movement direction to clientPlayerControl (internal to Client())
    11. Handle Pause
    12. Actual Game step()
        1. Process all Received Packets (ReceiveAll())
        2. Tell server about unloaded, unused blocks
        3. sendChatMessages
        4. m_env.step()
            1. Actually handles player Physics ****
            2. Then moves the player to the new position - which finds collisions
        5. Handle collisions found
        6. Handle Globalsteps (lua modding globalsteps for CSM)
        7. update CAO objects and lighting
        8. handle simple objects (CSO)
    13. Unholy C style Events processed in HandleClientEvents , types such as player damage, force_move, show_formspec, add_particle_spawner, set_sky, etc.
    14. Update debugState
    15. updateCamera - actully write out the camera values
    16. updateSound
    17. processPlayerInteraction -handle right and left mouse button dig/place clicks
    18. updateFrame
        1. clouds
        2. Particles
        3. Fog
        4. minimap
        5. chatMessages
        6. Inventory + wielded Item
        7. UpdateBlocksToDraw, Update shadows
        8. updateGui (just debug and chat? not sure here)
        9. handleFormspec, if that's a thing
        10. Draw the Frame
    19. update Profiler Graphs (now that frame has been drawn)
    20. Random minimap disable check
    21. ShowPauseMenu if paused

### Server

1. Server() constructor
    1. does a lot of normal setup (lots of managers started here)
    2. Creates the all-important ServerThread()
2. Server.start() 
    1. stops server thread if it's running
    2. initalizes networking
    3. starts the serverthread (asyncRunStep)
    4. Ascii Art 

### ServerThread - asyncRunStep() 
1. get dtime from main game thread or dedicated server function loop
2. handle Peer changes (client join and leave, creates ClientInterface()s to track them)
3. ServerEnvironment()::step()
    1. Increment Game time
    2. Handle player move
    3. Manage active block list
    4. Handle Active Blocks Nodetimers
    5. Handle ABMs
    6. Scripting Environment step (globalsteps)
    7. Async Engine step (for other lua threads we might have spawned)
    8. Server Active Object (SAO) Step
        1. weird lambda construct, but calls step on the object and dumps messages from it to a queue
    9. Manage SAO and particle spawner expiration
    10. warn lcients about invalid inventories, modified mapblocks (lua callbacks here)

**Comment by ExeVirus** [comment]
# Minetest Engine in a nutshell
```mermaid
flowchart LR
Main["Main.cpp - main()"] -->|Creates| Server["Server"]
Server --> ServerThread["ServerThread.cpp::asyncRunStep()"]
Main --->|Creates| Client["Client"]
```
## Main cpp
```mermaid
flowchart LR
subgraph Main["Main.cpp - main()"]
    args["1 Loads Arguments"] --> paths["2 Initializes paths"]
    paths --> com["3 Handles command line args for user help (list games, list worlds, etc)"]
    com --> lib["4 Library Init (Networking, seed random, curl, gettext)"]
    lib --> bench["5 Starts benchmarking, if enabled"]
    bench --> start["6 Either runs as headless server or standard client, which may or may not run a single player server"]
end
```
## Server
```mermaid
flowchart LR
subgraph Server ["Server"]
    subgraph serverC["Server() constructor"]
        setup["does a lot of normal setup (lots of managers started here)"] --> thread["Creates the all-important ServerThread()"]
    end
    serverC --> serverS
    subgraph serverS["Server.start()"]
        stopS["stops server thread if it's running"] --> initNet["initalizes networking"]
        initNet --> startST["starts the ServerThread (asyncRunStep)"]
        startST --> ascii["Ascii Art"]
    end
end
```
## ServerThread
```mermaid
flowchart LR
subgraph ServerThread ["ServerThread.cpp::asyncRunStep()"]
    getTime["get dtime from main game thread or dedicated server function loop"] --> handlePeer["handle Peer changes (client join and leave, creates ClientInterface()s to track them)"]
    handlePeer --> serverEnv
    subgraph serverEnv["ServerEnvironment()::step()"]
        direction TB
        incGt["Increment Game time"] --> handlePlayerM["Handle player move"]
        handlePlayerM --> MABM["Manage active block list"]
        MABM --> MABMNT["Handle Active Blocks Nodetimers"]
        MABMNT --> ABM["Handle ABMs"]
        ABM --> scriptEnvStep["Scripting Environment step (globalsteps)"]
        scriptEnvStep --> async["Async Engine step (for other lua threads we might have spawned)"]
        async --> SAO["Server Active Object (SAO) Step"]
        SAO --> MSAO["Manage SAO and particle spawner expiration"]
        MSAO --> warn["warn clients about invalid inventories, modified mapblocks (lua callbacks here)"]
    end
end
```
## Client
```mermaid
flowchart TB
subgraph Client ["Client"]
    direction TB
    subgraph ClientLauncher ["ClientLauncher().run()"]
        direction LR
        subgraph init_engine ["init_engine()"]
            ceventQueue["Create Event Queue"] --> crenderEngine["Create Rendering Engine"]
        end
        subgraph HandleMainMenu
            calls_the_game["Calls the_game() to run game"]
        end
        init_args["init_args() further"] --> init_engine
        init_engine --> createMainMenu["Create main menu"]
        createMainMenu --> HandleMainMenu
    end
    subgraph GameStartup["Game.cpp::startup()"]
        subgraph gameinit ["Game::init()"]
            direction TB
            createManagers["Creates textures, shaders, ItemDefManager, <br> NodeDefManager, EventManager (for game), Sound"] --> singplayer["Creates singleplayerserver if applicable"]
        end
        subgraph gameCreateClient ["Game::createClient()"]
            direction TB
            connectTo["Connect to server, get server content, update local caches after data received"] --> createStuff
            createStuff["Create camera, clouds, skybox"] --> initGui
            subgraph initGui ["Game::initGui()"]
                direction TB
                consoleOutput["Create debug text, chat text, info text, etc. (gameui.cpp)"] --> cgui["create GuiChatConsole"]
            end
            initGui --> hud["Create HUD"]
            hud --> initRenderingEng["Initialize RenderingEngine"]
        end
        gameinit --> gameCreateClient
    end
    subgraph GameRun["Game.cpp::run()"]
        direction TB
        updateDyn["updateDynamicInfo() - UI scaling, screen size, etc."] --> debugR
        debugR["update Debug render stats"] --> upPunch["update punch timers"]
        upPunch --> checkC["checkConnection() or fail"]
        checkC  --> handleC
        subgraph handleC["handleCallbacks() or fail"]
            hcnotes["These include disconnect, password_change, volume change, key config change"]
        end
        handleC --> processQ["process texture and shader queues (shader is empty for now)"]
        processQ --> upProf["updateProfilers()"]
        upProf --> ProcIo["ProcessUserInput() handles callbacks for each key, read from inputHandler's keycache variable"]
        ProcIo --> updateCamDir["updateCameraDirection() <br> (before movement, otherwise it looks like lag or something)"]
        updateCamDir --> updatePCtl["updatePlayerControl() <br> passes keys, camera pitch+yaw, movement speed, and movement direction to clientPlayerControl (internal to Client())"]
        updatePCtl --> handleP["Handle Pause"]
        handleP --> gamestep
        subgraph gamestep["Actual Game::step()"]
            direction TB
            rcv["Process all Received Packets - ReceiveAll()"] --> unusedB["Tell server about unloaded, unused blocks"]
            unusedB --> sendchatM["sendChatMessages()"]
            sendchatM --> envStep["Game::m_env.step() <br> 1. Actually handles player Physics <br> 2. Then moves the player to the new position - which finds collisions"]
            envStep --> handCollisions["Handle collisions found"]
            handCollisions --> csmGlobal["Handle Globalsteps (lua modding globalsteps for CSM)"]
            csmGlobal --> updateCAO["update CAO objects and lighting"]
            updateCAO --> updateCSO["handle simple objects (CSO)"]
        end
        gamestep --> unholyC["Unholy C style Events processed in HandleClientEvents, <br> types such as player damage, force_move, show_formspec, add_particle_spawner, etc."]
        unholyC --> updateDebug["Update debugState"]
        updateDebug --> updateCamera["updateCamera() - actully write out the camera values"]
        updateCamera --> updateSound["updateSound()"]
        updateSound --> processPI["processPlayerInteraction() <br>handle right and left mouse button dig/place clicks"]
        processPI --> updateFrame
        subgraph updateFrame["updateFrame()"]
            direction TB
            clouds --> Particles
            Particles --> Fog
            Fog --> minimap
            minimap --> chatMessages
            chatMessages --> inv["Inventory + wielded Item"]
            inv --> updateBlocksSh["UpdateBlocksToDraw, Update shadows"]
            updateBlocksSh --> updateGui["updateGui() - just debug and chat? not sure here"]
            updateGui --> handleForm["handleFormspec, if that's a thing"]
            handleForm --> draw["Draw the Frame"]
        end
        updateFrame --> updateProfilerGraphs["update Profiler Graphs (now that frame has been drawn)"]
        updateProfilerGraphs --> rmini["Random minimap disable check"]
        rmini --> pause["ShowPauseMenu if paused"]
    end
    ClientLauncher --> GameStartup
    GameStartup --> GameRun
end
```

**Comment by ExeVirus** [comment]
## Notes for future me: 

1. Schedule is always delayed:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
</head>

<body link="#0563C1" vlink="#954F72">



Time | Plan |   | Time | Actual
-- | -- | -- | -- | --
8:00 | Arival + Setup |   | 8:00 | Arrival + Setup Dev   Environment
8:30 | Goal Setting, Design   Work |   | 8:45 | Play with Minetest -   setup test world
9:30 | Setup Dev environment |   | 8:55 | Goal setting, Design   Work
10:00 | Locate and Plan   Class/Spots for connection |   | 9:45 | Locate and Plan   Class/Spots for connection
10:30 | Begin Scaffolding |   | 10:40 | Break, Scaffolding
11:30 | First compile, start   lua environment |   | 11:00 | Learn the Entire   Engine
12:00 | Provide all needed   inputs to lua environment |   | 2:30 | Tired. Going home
12:30 | Provide Output spots   from lua environment |   |   |  
1:00 | Create lua file   loading method (media or otherwise) |   |   |  
1:30 | Connect registration   to server-side at startup |   |   |  
2:00 | Create 2+ physics   styles |   |   |  
3:00 | Code Guidelines,   Cleanup, Merge Request |   |   |  
4:00 | Head home |   |   |  



</body>

</html>


2. The spots to modify on the client are: 
    - game::run() -> updateCameraDirection (possibly)
    - game::run() -> updatePlayerControl
        - Pass in more variables, make camera modifiably passed in
    - game::m_env::step() -> to actually handle physics here
        - connect to new class
    - possibly handle collisions differently - we'll see.
        - would require a second callback in the physics lua file

3.  Server spots are:
    - add the lua_environment function connections
    - handle Player move

**Comment by kno10** [comment]
Physic specifications and some way to map them to nodes and entities would be powerful.

Consider gravity vs. swimming in water. With high dtime, we get items and mobs "trampolining" on water, because gravity is applied for a too long timestep so they submerge, and then updrift is applied for too long, too.
If there was a map that specified that air = physics 0, water = physics 1, the engine could probably handle the change in gravity within a timestep.
Changing physics from lua side may be too coarse.

**Comment by ExeVirus** [comment]
Explain how changing settings from the Lua side is different from changing
what functionality happens from the Lua side are actually different?

**Comment by kno10** [comment]
Lua code runs every dtime step, handling physics within, e.g., the collision code will have sub-dtimestep-resolution.
Hence less trampolining if physics change similarly.

**Comment by ExeVirus** [comment]
Ah,

That's absolutely true. Ideally there would be like 6 hard coded options,
and then a Lua option for completely custom physics. And* collision would
be separately from each standard entity step.

However, I still say we should provide fully lua-flexible physics as an
option. It's a key piece of being a good engine.

**Comment by appgurueu** [comment]
> I still say we should provide fully lua-flexible physics as an option. It's a key piece of being a good engine.

I absolutely agree.

> Lua code runs every dtime step, handling physics within, e.g., the collision code will have sub-dtimestep-resolution.

This is not a given. We can have a physics step Lua callback on the client which runs more often. Löve2d for example does this: There is `love.update` which tends to run at a much higher tick rate than `love.draw`.

> looking at the number of issues complaining about our 1 supported physics style: [...]

Our player movement physics suck and are a nightmare to work on.
I think we might need to construct an entirely separate clean, alternative physics system from the ground up once we have SSCSM.

Modders should not need to opt out of various aspects of some kind of vaguely specified movement physics - they should opt in explicitly to those features they want, and implement fancier features themselves in pure Lua.

Otherwise we're in for a world of hurt as players expect full backwards compatibility of movement code - when it is not even clear what the movement code is supposed to be doing, and tiny changes can have very unexpected side effects.
