### ISSUE TITLE
ContentDB redesign to-do list

### ISSUE THREAD

**Issue by grorp** [minetest/minetest#15241]
- [ ] Android: respect display insets instead of hardcoded extra padding (I already implemented this, need to PR it)

Package list
- [ ] Don't show unusable scrollbar when short descriptions overflow (short term fix)
- [ ] Move ContentDB image loading to C++ #14953

Package dialog
- [ ] Don't wait for full package info to load before showing basic info and install button
- [ ] Reviews tab

Feel free to expand.

**Comment by rubenwardy** [comment]
I think it might be a good idea to make num per page fully dynamic, allowing the package grid algorithm to run in a single step. Currently, it runs in two steps - finding the num_per_page at load time, and finding columns/cell size at formspec build time.

To do this, instead of storing current page number it should store a start index. So when resizing the window, it may show a different number of items on the current page but would always show the same item at the start of the page. This may result in weirdness when the current index doesn't align with the pages, but would fix itself when doing < or >.

Using a start index rather than page number prevents the user from losing their place when resizing the window

**Comment by swagtoy** [comment]
for the scrollbar issue, it should just use ellipses or something. Or try to stop at the first period it can without overflowing.

**Comment by swagtoy** [comment]
Once the C++ image loading is done, being able to open the images in a carousel view would be great

**Comment by GoodClover** [comment]
Could I request it be possible to filter per-game?
So, "show me texture packs for NodeCore".  This already exists on the Website.
The current UI of lumping all packages for everything in one list is annoying to navigate.

**Comment by rubenwardy** [comment]
> Could I request it be possible to filter per-game? So, "show me texture packs for NodeCore". This already exists on the Website. The current UI of lumping all packages for everything in one list is annoying to navigate. A drop-down of installed games next to the search bar could be one way of doing this.

The issue for this is: #13851

**Comment by siliconsniffer** [comment]
Suggestion: add a change log tab or show the change log for the latest version (like the website does it) in an existing one.

**Comment by programmerjake** [comment]
I'd like to bring back the install button directly on the list of mods, that way if you're using a new luanti install and are going through the list to install all your favorite mods you don't have to click on each mod, wait for the mod's info page to load, move your mouse all the way to the corner, click install, go back, and click on the next mod.

alternatively, maybe just allow selecting multiple mods (checkboxes on the mods list) then you can click install, uninstall, etc. on all of them at once, that could also help with choosing all their dependencies at once in one big list rather than after clicking install on each mod.
