### ISSUE TITLE
[CSM] Second Roadmap

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#5394]
Here is the main roadmap and discussion topic about CSM.

Please post your ideas here, or open a new issue linked back with it. It will permit developers to centralize requested features and priorize them.

# Feature requests
## Short term
__Documentation is mandatory for each PR__

* [x] Localplayer reference (#5480)
* [x] Mod storage (#5396)
* [ ] Hud (more precisions needed, at least text hud with reference)
* [x] Minimap API (modes + position) (#5399)
* [ ] Enable/Disable mod from main menu
* [ ] Particles (#5492)
* [x] Add a function to generate minetest color codes (#5113)
* [x] on_place_node callback (#5548)
* [x] on_item_use callback (#5544)
* [x] Camera API (#5609)
* [x] `core.get_timeofday` and `core.get_day_count` (#5401)
* [x] `core.get_node_level`, `core.get_node_max_level`, `core.find_node_near` (#5401)
* [ ] Minimap API: change size
* [x] on_connected callback (when player is in world)
* [x] NodeMeta refs (#5508)
* [x] core.on_connect (#5540)
* [ ] Loading local mods medias (after server mod medias)

## Longer Term
* [ ] Mod channels (#5390)
* [ ] Mod loading from server side (#5393)
* [ ] Keymap customization (maybe builtin instead of hardcoded keymap formspec)
* [ ] Input event listening
* [x] core.disconnect
* [ ] Toggle many Game flags 
* [ ] Mod meta informations (version, minimum MT version required, maximum, maintainer (nick, mail) using json

# Reported bugs
* [x] core.sound_play wrong interface (#5389)
* [x] Minimap Show/hide doesn't work properly (#5422)

# Other
* [ ] Client mod store

**Comment by octacian** [comment]
* HUDs (I assume this is a given, but)
* Ability to get node meta (or has this already been implemented?)

What I'd really love for CSM is the ability to define an API (e.g. for easier creation of HUDs, as I'm doing with my HUD Plus mod) on a server-side mod and then use that API on the client. This would allow (for example) registering an HUD using my custom API to display the description of the item in the hotbar. Another thing that could be important in relation to this is an extra API function on the server-side to check for a specific mod on the client. I'm not sure how realistic the first thing is, but just throwing it out there (that's what this issue is for, right? :P)

**Comment by nerzhul** [comment]
@octacian it's not easy for HUD, we could customize HUD in the near future but this should not depend on server side attributes.

**Comment by red-001** [comment]
- [ ] Add more interaction related callbacks E.g. on_place_node, on_item_use
- [ ] Port more node related getters E.g. minetest.get_node_timer
- [ ] Add a function to generate minetest color codes
- [ ] Get the current player name

**Comment by nerzhul** [comment]
@red-001 i picked some ideas from your comment to the main list

**Comment by sofar** [comment]
I don't think node timers are sent to the client. Node meta, yes, node timers, no.

**Comment by nerzhul** [comment]
@sofar yes, maybe we can have local node timers for something ? example: particles created every 1 sec on a node ?

**Comment by C1ffisme** [comment]
I'm not sure how difficult this would be to make, or even turn into a usable API, but what about being able to render certain objects for each player, such as fishing line or lightning?

**Comment by sofar** [comment]
`minetest.register_on_joinplayer`
`minetest.register_on_leaveplayer`
`minetest.get_connected_players`
`minetest.player_exists`

all reasonable CSM interfaces imho.

**Comment by nerzhul** [comment]
@sofar i think yes, but at this moment if i remember client doesn't know which player is connected, only server knows it. But client knows somewhere some CAO are client because it shows names everywhere

**Comment by sofar** [comment]
Timers on client nodes seems risky, the client's perspective of the world is very different and it keeps huge amounts of map in memory.

However, if the timers can be for arbitrary nodes, and we can implement some sort of "active range" to the localplayer, it could work very well to periodically loop sounds or add particles

**Comment by nerzhul** [comment]
@sofar sounds be more reasonable, like ABM range

**Comment by raymoo** [comment]
What about creating CAOs that are simulated on the client, and not tied to a SAO? They could he used for visual effect, e.g. put a colored box around a selected target.

**Comment by nerzhul** [comment]
@raymoo i don't think it's a CAO, maybe an attached entity

**Comment by raymoo** [comment]
It doesn't matter to me if it's technically a CAO, I just assumed something like this would be implemented as a CAO. I just want something similar to a LuaSAO that can be simulated on the client and can have its behavior specified in Lua.

I don't think it should be limited to being attached, for example if you wanted to interpolate the entity's position. You could imagine implementing this as a hard-coded flag, but you would have trouble covering every kind of similar feature someone might want to use.

**Comment by bigfoot547** [comment]
Here are some features I hope are added.
 - [ ] minetest.colorize
 - [ ] Client HUD
 - [ ] Server time of day?
 - [ ] Client particles
 - [ ] Closing formspecs of local player?
 - [ ] Get the name of local player and maybe list of players if possible?
 - [ ] Get health and breath and player attributes of local player
 - [ ] Pointed node / object ref and maybe liquid of local player
 - [ ] Set fov of local player

That is a list of intresting features that I think are worth working on and eventually adding.
Thanks!

**Comment by nerzhul** [comment]
@bigfoot547 i think we can have registered_items, it could be useful to have a pure client side craft guide

**Comment by nerzhul** [comment]
I renamed it to second roadmap, to have a second patchset as a changelog to core, when this patchset will be finished, we will close this issue and re-open another issue to follow the new changes

**Comment by octacian** [comment]
Kinda reiterating the same thing @bigfoot547 said, but figured I'd say it anyways.

IMO, `minetest.colorize` is very important when paired up with an API to get the name of the player. With those two things, one could make a mod (as I was hoping to do) which would notify the player whenever they received a message with their name in it.

The ability to get all the other players on the server would open the door for a custom overview formspec to be displayed with a list of all players and maybe even a search bar. 

A client-side craft guide would also be so useful seeing as it'd be practically lag-free.

**Comment by nerzhul** [comment]
@octacian i understand what you need and i need to rewrite the chat protocol to be more intelligent to do more interesting things :)

**Comment by bigfoot547** [comment]
@octacian On servers, people refer to me as big foot, bigfoot and bf. Only when the feel like pressong tab do they call me bigfoot547.

**Comment by DS-Minetest** [comment]
(Also good would be a nice documentation. `client_lua_api.md` (why here `.md`?) nearly consists out of wrong information.)

And `minetest.get_modpath` is needed, too.

**Comment by nerzhul** [comment]
We use .md for better reading especially on github.You are free to help us to fix the doc. Why do you need et mod path ? We don't port it because on client API os very restricted but maybe we forget something

**Comment by octacian** [comment]
- [ ] `minetest.get_timeofday` would allow me to improve my WIP ambiance mod

**Comment by DS-Minetest** [comment]
I meant, `minetest.get_modpath` for clientmods. So, something like `minetest.get_clientmodpath`. This could be used for nice folder structures (with `dofile`).

**Comment by nerzhul** [comment]
in a discussion we had on CSM PR #5088 dofile is not inteded to be used but require instead, we should study this

**Comment by Rui-Minetest** [comment]
- [ ]  HTTP Request API
- [ ] ’set_bone_position

**Comment by Rui-Minetest** [comment]
- [ ] HTTP API
- [ ] `set_bone_position` (or something like `get_localplayer`)
- [ ] `set_player_velocity`

**Comment by sofar** [comment]
FYI sound (API fixes) and particles are highest on my request list... without them, ambiance mods are going to be bleak no matter what.

**Comment by nerzhul** [comment]
@Rui-Minetest i don't think we will add HTTP API to client as it's a very high security risk to permit random HTTP requests from clients, especially if at a point we send mods from server, this could deserve a DDoS vector. I don't add it for the second roadmap.

@sofar no problem, you are also free to develop it, priority is for all users, but it doesn't mean we will refuse a PR if other priority PR are not fixed :)

@Rui-Minetest why set bone position and velocity ? It's a pure server owning feature. We will have minetest.localplayer reference at a point

**Comment by sofar** [comment]
FOV setting is broken. Somehow it's resetting on my machine.

Minimap also can't be round anymore, which I preferred.

**Comment by nerzhul** [comment]
@sofar i'm looking to fix this, i don't know about the FOV setting, how does it works ?
For round minimap just disable preview mod if you doesn't want it

**Comment by nerzhul** [comment]
@sofar tested the switch using CTRL+F9 it works fine.
For FOV CSM don't manage FOV

**Comment by Fixer-007** [comment]
What about get_node_light ? Will be useful for bigfoot's inspect mod.

**Comment by DS-Minetest** [comment]
@Fixer-007 I thought node light was saved in `param1`.
Punch and co. would need to give `pointed_thing`, then you could get the `param1` of the node on pos `pointed_thing.above`...

**Comment by XtremeHacker** [comment]
I would like to see a system to register your own recipe type, as at the moment hacky solutions are needed for custom crafting recipe types.
(Saved for when I re-remember all the ideas I had)

**Comment by rubenwardy** [comment]
@XtremeHacker offtopic

**Comment by XtremeHacker** [comment]
@rubenwardy Sorry, didn't notice CSM, I'll remove my previous comment, thought this was a general roadmap.

**Comment by Wuzzy2** [comment]
I agree with DS-Minetest. The current documentation looks very incomplete/incorrect to me. To quote myself from the forums:

> Sorry, but this looks very very WIP and most of it looks just like copypasted from lua_api.md. Not even the introduction is correct:
>
>> Mods are contained and ran solely on the server side. Definitions and media files are automatically transferred to the client.
>
> Also not much about the capabilities of this feature is explained, especially the difference from “normal” modding. Sorry, with this document you can't complain about users ignoring it, because it is not really useful at this stage. Linuxdirk was completely right in complaining about the lack of proper documentation.

**Comment by sofar** [comment]
> I think a correct documentation is very important and it should definitely go to the roadmap.

agreed. Please add it to the "short term" list for improvement. It certainly could use some more text already, and things like general information about the feature would fit in well in the client mod api text as an introduction at the top.

**Comment by nerzhul** [comment]
added

**Comment by red-001** [comment]
#5467

**Comment by Dumbeldor** [comment]
#5480

**Comment by red-001** [comment]
#5492

**Comment by raymoo** [comment]
Issues in the past that I've seen so far where someone has suggested waiting for client side scripting so mods can implement:
#4700 

I can't think of a good way to find all of these, but I know there's at least a few more.

**Comment by raymoo** [comment]
This one (#4366) is related, specifically the part about custom physics models for entities.

**Comment by raymoo** [comment]
What about client side lua active objects? Things that are meant to be visual effects or UI elements.

Sample ideas (both require client<=>server communication to be useful):
 - Display a heart above allies in some faction system
 - Player uses magic activator. A magic circle expands around the player, with nodes around the rim representing options. The player can walk into an option, which sends a message to the server that the player chose a particular option (and the server can handle the choice at that point).

Both of these could be implemented alternatively with selective visibility of server objects, but since these are only displayed to one client and have minimal interaction with other elements of the server, they could be client-local to reduce display lag.

**Comment by nerzhul** [comment]
display informations on CAO is a nice CSM behaviour we should have, for the other point it's more server responsiblity

**Comment by cdqwertz** [comment]
I would love to have some sort of system to call a function when a key is pressed.
```lua
core.bind(<key/event>, <function>)
```

**Comment by red-001** [comment]
#5532

**Comment by bigfoot547** [comment]
#5569

**Comment by sofar** [comment]
As noted in the particle PR, it seems that CSM assets are not loaded. This makes it impossible for CSM mods to ship their own textures.

This is a fundamental issue that will affect sounds as well.

@nerzhul @red-001

**Comment by nerzhul** [comment]
@sofar loadMedia is only done by server sent packet atm, we should add same feature at mod loading from client side

**Comment by sofar** [comment]
Yup, I figured - add it to the worklist above? it's pretty crucial.

**Comment by sofar** [comment]
![](http://i.imgur.com/X2BZI0C.jpg)

Standing in lava - no damage.

**Comment by nerzhul** [comment]
we can add it, but i don't if i will have time myself to manage this, as i have many PR which are crucial outside CSM and should be merged

**Comment by bigfoot547** [comment]
#5609

**Comment by red-001** [comment]
if a way to send mods form the server is added we should also send back error messages to the server, so server admins can debug mod crashes.

**Comment by DS-Minetest** [comment]
What about a per-world store?

**Comment by HybridDog** [comment]
rendeko wrote something about allowing custom huds: https://forum.minetest.net/viewtopic.php?p=269253#p269253
How about adding a function register_on_formspec_show(function(spec)) which makes it possible to adjust a formspec (e.g. change background) before showing it to the player?

**Comment by CasimirKaPazi** [comment]
Would it be also possible to override item descriptions? That would be an easy way to get client side item translations.

**Comment by HybridDog** [comment]
You could change the "description" meta field of an item client-side.

**Comment by nerzhul** [comment]
This roadmap will be closed on feature freeze, on 21st may. A new will be opened after releasing MT

**Comment by nerzhul** [comment]
I'm closing this roadmap as the feature freeze occurs this evening. Thanks all for your participation
