### ISSUE TITLE
List of Lua API issues

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#6557]
The lua_api.txt file has a ton of issues. I created this issue to keep track of them, and to encourage them to be fixed

## Hud

- [ ] alignment is a vector, not a number
- [ ] aligning to the left is actually aligning to the right with images
- [ ] still experimental?

## Objects

- [ ] What do each of the 6 indices of "collisionbox" relate to? #6526 
- [ ] What do the different choices for "visual" mean? #6526

## Metadata

- [ ] Document that values are stored as strings, then cast on demand #6492

## Registration Tables

- [ ] Parameters to an ABM's func aren't documented #6507

**Comment by rubenwardy** [comment]
-> #5854
